# Generated by Django 4.2.7 on 2025-11-19 20:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UsageRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "billing_period_start",
                    models.DateField(help_text="Start date of billing cycle"),
                ),
                (
                    "billing_period_end",
                    models.DateField(help_text="End date of billing cycle"),
                ),
                (
                    "data_used_mb",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Data consumed in megabytes",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "data_limit_mb",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Data allowance in megabytes (NULL = unlimited)",
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "minutes_used",
                    models.IntegerField(
                        default=0,
                        help_text="Voice minutes consumed",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "minutes_limit",
                    models.IntegerField(
                        blank=True,
                        help_text="Minutes allowance (NULL = unlimited)",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "sms_used",
                    models.IntegerField(
                        default=0,
                        help_text="SMS count",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "sms_limit",
                    models.IntegerField(
                        blank=True,
                        help_text="SMS allowance (NULL = unlimited)",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_records",
                        to="customers.customer",
                    ),
                ),
            ],
            options={
                "db_table": "usage_records",
                "ordering": ["-billing_period_end"],
                "indexes": [
                    models.Index(
                        fields=["customer", "-billing_period_end"],
                        name="usage_recor_custome_68ee53_idx",
                    ),
                    models.Index(
                        fields=["billing_period_start", "billing_period_end"],
                        name="usage_recor_billing_42c175_idx",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="usagerecord",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("billing_period_end__gte", models.F("billing_period_start"))
                ),
                name="billing_period_dates_check",
            ),
        ),
    ]
