# Generated by Django 4.2.7 on 2025-11-20 04:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0002_alter_account_customer"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customer",
            options={"ordering": ["created_at"]},
        ),
    ]
